### ISSUE TITLE
Lista TO-DO // A fazeres nas futuras versões

### ISSUE THREAD

**Issue by randomCoolProjects** [randomCoolProjects/MasterChat#1]
- [ ] **VERSÃO 1.5:**

  - [ ] Esconder data e horário de envio das mensagens - Mostrar apenas quando passar o cursor em cima

  - [ ] Privilégios de admininstrador

  - [ ] Banir usuários

  - [ ] Resolver bug do timeout

  - [ ] Melhorar UI de login

  - [ ] Recursos de segurança - prevenir ataques XSS (client-side) -- somente o admin pode enviar HTML

- [ ] **VERSÃO 1.9:**

  - [ ] Novo nome para o APP/Chat

  - [ ] Possibilitar instalação de temas

  - [ ] Masterchat Marketplace

  - [ ] Permitir envio de arquivos e leve formatação de texto -- HTML automático

- [ ] **VERSÃO 2.0**

   - [ ] Sistema de sala privada com usuários
